'''Controlled vocabulary for revision records.'''

from enum import Enum


class StringEnum(str, Enum):
    '''Enum whose serialized representation is its stable string value.'''


class ReviewerSource(StringEnum):
    EDITOR = 'EDITOR'
    REVIEWER = 'REVIEWER'
    GENERAL = 'GENERAL'


class CommentPriority(StringEnum):
    CRITICAL = 'CRITICAL'
    MAJOR = 'MAJOR'
    MINOR = 'MINOR'


class CommentCategory(StringEnum):
    ABSTRACT = 'ABSTRACT'
    INTRODUCTION = 'INTRODUCTION'
    LITERATURE = 'LITERATURE'
    NOVELTY = 'NOVELTY'
    METHODOLOGY = 'METHODOLOGY'
    MATHEMATICAL_FORMULATION = 'MATHEMATICAL_FORMULATION'
    EXPERIMENTAL_DESIGN = 'EXPERIMENTAL_DESIGN'
    STATISTICS = 'STATISTICS'
    RESULTS = 'RESULTS'
    COMPARISON = 'COMPARISON'
    ROBUSTNESS = 'ROBUSTNESS'
    STEGANALYSIS = 'STEGANALYSIS'
    COMPLEXITY = 'COMPLEXITY'
    IMPLEMENTATION = 'IMPLEMENTATION'
    FIGURES = 'FIGURES'
    TABLES = 'TABLES'
    EQUATIONS = 'EQUATIONS'
    REFERENCES = 'REFERENCES'
    LANGUAGE = 'LANGUAGE'
    FORMATTING = 'FORMATTING'
    LIMITATIONS = 'LIMITATIONS'
    CONCLUSION = 'CONCLUSION'
    GENERAL = 'GENERAL'


class RevisionStatus(StringEnum):
    NOT_STARTED = 'NOT_STARTED'
    ANALYZED = 'ANALYZED'
    PLANNED = 'PLANNED'
    DRAFTED = 'DRAFTED'
    APPLIED = 'APPLIED'
    VERIFIED = 'VERIFIED'
    DEFERRED = 'DEFERRED'
    NOT_APPLICABLE = 'NOT_APPLICABLE'


class EvidenceStatus(StringEnum):
    NOT_REQUIRED = 'NOT_REQUIRED'
    REQUIRED = 'REQUIRED'
    MISSING = 'MISSING'
    PROVIDED = 'PROVIDED'
    VERIFIED = 'VERIFIED'
    REJECTED = 'REJECTED'


class ResultStatus(StringEnum):
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    DRAFT = 'DRAFT'
    UNVERIFIED = 'UNVERIFIED'
    VERIFIED = 'VERIFIED'
    FINAL = 'FINAL'


class ApprovalState(StringEnum):
    NOT_REQUIRED = 'NOT_REQUIRED'
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    REVISION_REQUESTED = 'REVISION_REQUESTED'


class CoverageStatus(StringEnum):
    FULLY_ADDRESSED = 'FULLY_ADDRESSED'
    PARTIALLY_ADDRESSED = 'PARTIALLY_ADDRESSED'
    NOT_ADDRESSED = 'NOT_ADDRESSED'
    NOT_APPLICABLE = 'NOT_APPLICABLE'
    CANNOT_DETERMINE = 'CANNOT_DETERMINE'


class ApprovalDecision(StringEnum):
    APPROVE = 'APPROVE'
    APPROVE_WITH_MODIFICATION = 'APPROVE_WITH_MODIFICATION'
    REJECT_WITH_JUSTIFICATION = 'REJECT_WITH_JUSTIFICATION'
    NEED_MORE_EVIDENCE = 'NEED_MORE_EVIDENCE'
    DEFER = 'DEFER'


class ApprovalGateStatus(StringEnum):
    NOT_READY = 'NOT_READY'
    READY_FOR_REVIEW = 'READY_FOR_REVIEW'
    PARTIALLY_APPROVED = 'PARTIALLY_APPROVED'
    APPROVED = 'APPROVED'
    BLOCKED = 'BLOCKED'


class HighlightColor(StringEnum):
    YELLOW = 'YELLOW'
    BRIGHT_GREEN = 'BRIGHT_GREEN'
    VIOLET = 'VIOLET'


class ChangeType(StringEnum):
    ADDITION = 'ADDITION'
    REWRITE = 'REWRITE'
    DELETION = 'DELETION'
    RELOCATION = 'RELOCATION'
    REFERENCE_ADDITION = 'REFERENCE_ADDITION'
    REFERENCE_CORRECTION = 'REFERENCE_CORRECTION'
    FIGURE_REVISION = 'FIGURE_REVISION'
    TABLE_REVISION = 'TABLE_REVISION'
    EQUATION_REVISION = 'EQUATION_REVISION'
    FORMATTING = 'FORMATTING'
    EXPERIMENTAL_ADDITION = 'EXPERIMENTAL_ADDITION'
    STATISTICAL_ANALYSIS = 'STATISTICAL_ANALYSIS'
    GENERAL_CORRECTION = 'GENERAL_CORRECTION'
